#!/usr/bin/python3
import subprocess

tab1 = """Cviceni:Bodu:Projekt
Prvni programy:0:
Cyklus, typy:0:
Retezce:0:
Funkce 1:0:
Struktury:2:
Ukazatele:2:
Funkce:0:Obhajoba 1
Malloc, dbg:2:
:0:
:0:
Iterace, rekurze:2:
:0:Obhajoba 2
Dynamicke struktury:2:"""

tab2 = """Tyden:Cviceni:Bodu:Projekt
:Prvni programy:0:
:Cyklus, typy:0:
:Retezce:0:
:Funkce 1:0:
:Struktury:2:
:Ukazatele:2:
:Funkce:0:Obhajoba 1
:Malloc, dbg:2:
::0:
::0:
:Iterace, rekurze:2:
::0:Obhajoba 2
:Dynamicke struktury:2:"""

tab3 = """Tyden:Cviceni:Bodu:Projekt
1:Prvni programy:0:
2:Cyklus, typy:0:
3:Retezce:0:
4:Funkce 1:0:
5:Struktury:2:
6:Ukazatele:2:
7:Funkce:0:Obhajoba 1
8:Malloc, dbg:2:
9::0:
10::0:
11:Iterace, rekurze:2:
12::0:Obhajoba 2
13:Dynamicke struktury:2:"""

tab4 = """Tyden:Cviceni:Bodu:Projekt
1:Prvni programy:0:
2:Cyklus, typy:0:
3:Retezce:0:
4:Funkce 1:0:
5:Struktury:2:
6:Ukazatele:2:
7:Funkce:0:Obhajoba 1
8:Malloc, dbg:2:
9::0:
10::0:
11:Iterace, rekurze:2:
12::0:Obhajoba 2
13:Dynamicke struktury:2:
:celkem bodu::"""

tab5 = """Tyden:Cviceni:Bodu:Projekt
1:Prvni programy:0:
2:Cyklus, typy:0:
3:Retezce:0:
4:Funkce 1:0:
5:Struktury:2:
6:Ukazatele:2:
7:Funkce:0:Obhajoba 1
8:Malloc, dbg:2:
9::0:
10::0:
11:Iterace, rekurze:2:
12::0:Obhajoba 2
13:Dynamicke struktury:2:
:celkem bodu:10:"""

subprocess.call("./sheet -d : icol 1 <tab1.txt >tab1a.txt; ./sheet -d : rows 1 1 cset 1 Tyden <tab1a.txt >tab2.txt", shell = True)
with open("tab2.txt","r") as f:
    if f.read()!=tab2:
        print("./sheet -d : icol 1 <tab1.txt >tab1a.txt; ./sheet -d : rows 1 1 cset 1 Tyden <tab1a.txt >tab2.txt")
        print("Error in Tab2, diffni si to :*")
        exit(-1)

subprocess.call("./sheet -d : rseq 1 2 - 1 <tab2.txt >tab3.txt", shell = True)
with open("tab3.txt","r") as f:
    if f.read()!=tab3:
        print("Error in Tab3, no aspoň tab2 byl v klidu :D")
        exit(-1)

subprocess.call("./sheet -d : arow <tab3.txt >tab3a.txt; ./sheet -d : rows - - cset 2 \"celkem bodu\" <tab3a.txt >tab4.txt", shell = True);
with open("tab4.txt","r") as f:
    if f.read()!=tab4:
        print("Error in Tab4, almost... :juraj: :smrkbat:")
        exit(-1)

subprocess.call("/sheet -d : rsum 3 2 14 <tab4.txt >tab5.txt", shell = True)
with open("tab5.txt","r") as f:
    if f.read()!=tab5:
        print("Error in Tab5, :vojtakokoti:")
        exit(-1)


