name: C
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: ls ; make
    - name: make debug
      run: make dbug
